### PR TITLE
Add RBI support

### PR DESCRIPTION
**Pull request by thomasmarshall**
This PR adds support for RBI files. This could be useful for sharing or reproducing RBI specific functionality (e.g. sig overloads). It uses a new `--rbi` command line arg, so requires a new build of sorbet-wasm. I've added a temporary commit with my custom sorbet-wasm build based off [this PR](https://github.com/sorbet/sorbet/pull/7977), but can remove that and add a real build before merging.

https://github.com/sorbet/sorbet.run/assets/770763/50c016aa-7f09-4e0e-a9ca-8e9bc70a05ef

### CODE REVIEW

**Comment by thomasmarshall** [comment]
Here's a video demonstrating "go to definition" but it relies on a workaround using an internal Monaco API. I tried to update `monaco-editor-core` to make use of [this PR](https://github.com/microsoft/vscode/pull/177064) which adds proper support for go-to-definition, but that meant updating a ton of other packages too and addressing various breaking changes. If the workaround isn't suitable then I will come back to this PR later when the dependencies are updated—maybe I can take a look at doing that separately.

https://github.com/sorbet/sorbet.run/assets/770763/c8ff45b9-d835-4a81-be2c-9e100a9bb50e

**Comment by thomasmarshall** [comment]
What do you think @jez? If the workaround isn't suitable then I'll probably close this PR because upgrading Monaco is not straightforward.

**Comment by jez** [comment]
Hey I think that now that [this PR](https://github.com/sorbet/sorbet/pull/7979) has landed, people can use `# typed: __STDLIB_INTERNAL` as a way to test method overloads on sorbet.run.

Given the current approach in this PR requires compromises, I'm inclined to just leave it as is, and direct people to use `# typed: __STDLIB_INTERNAL` to test overloads in sorbet.run

**Comment by thomasmarshall** [comment]
OK that makes sense, thanks.

**Pull request closed without merging**
